# Name: Rebecca Walker
# Date: 3/5/21
# Program Name; Dice Roller
# Description: This program uses turtle to create 6 die then it creates two more
# with a random die number and calculates the probability of rolling that sum of die.

import turtle
import random

def main():
    
    turtle.setup(800,600)
    win = turtle.Screen()
    win.bgcolor("LightPink")

    width = 100
    dice = turtle.Turtle()
    dice.speed(0)
    DieValue = 1

    for x in range (-380, 390, 130):
        dice.penup()
        dice.goto(x,50)
        dice.pendown()
        dice.fillcolor("white")
        dice.begin_fill()
        
        for i in range (4):
            dice.forward(width)
            dice.right(90)
        dice.end_fill()
            
        if DieValue == 1:
            dice.penup()
            dice.goto(-330, -5)
            dice.fillcolor("Black")
            dice.pendown()
            dice.begin_fill()
            dice.circle(width // 15)
            dice.end_fill()
        elif DieValue == 2:
            dice.penup()
            dice.goto(-225, -30)
            dice.fillcolor("Black")
            dice.pendown()
            dice.begin_fill()
            dice.circle(width // 15)
            dice.end_fill()
            dice.penup()
            dice.goto(-175, 20)
            dice.pendown()
            dice.begin_fill()
            dice.circle(width // 15)
            dice.end_fill()
        elif DieValue == 3:
            dice.penup()
            dice.goto(-95, -30)
            dice.fillcolor("Black")
            dice.pendown()
            dice.begin_fill()
            dice.circle(width // 15)
            dice.end_fill()
            dice.penup()
            dice.goto(-70, -5)
            dice.pendown()
            dice.begin_fill()
            dice.circle(width // 15)
            dice.end_fill()
            dice.penup()
            dice.goto(-45, 20)
            dice.pendown()
            dice.begin_fill()
            dice.circle(width // 15)
            dice.end_fill()
        elif DieValue == 4:
            dice.penup()
            dice.goto(35, 20)
            dice.fillcolor("Black")
            dice.pendown()
            dice.begin_fill()
            dice.circle(width // 15)
            dice.end_fill()
            dice.penup()
            dice.goto(35, -30)
            dice.pendown()
            dice.begin_fill()
            dice.circle(width // 15)
            dice.end_fill()
            dice.penup()
            dice.goto(85, 20)
            dice.pendown()
            dice.begin_fill()
            dice.circle(width // 15)
            dice.end_fill()
            dice.penup()
            dice.goto(85, -30)
            dice.pendown()
            dice.begin_fill()
            dice.circle(width // 15)
            dice.end_fill()
        elif DieValue == 5:
            dice.penup()
            dice.goto(165, 20)
            dice.fillcolor("Black")
            dice.pendown()
            dice.begin_fill()
            dice.circle(width // 15)
            dice.end_fill()
            dice.penup()
            dice.goto(165, -30)
            dice.pendown()
            dice.begin_fill()
            dice.circle(width // 15)
            dice.end_fill()
            dice.penup()
            dice.goto(190, -5)
            dice.pendown()
            dice.begin_fill()
            dice.circle(width // 15)
            dice.end_fill()
            dice.penup()
            dice.goto(215, 20)
            dice.pendown()
            dice.begin_fill()
            dice.circle(width // 15)
            dice.end_fill()
            dice.penup()
            dice.goto(215, -30)
            dice.pendown()
            dice.begin_fill()
            dice.circle(width // 15)
            dice.end_fill()
        else:
            dice.penup()
            dice.goto(295, 20)
            dice.fillcolor("Black")
            dice.pendown()
            dice.begin_fill()
            dice.circle(width // 15)
            dice.end_fill()
            dice.penup()
            dice.goto(295, -5)
            dice.pendown()
            dice.begin_fill()
            dice.circle(width // 15)
            dice.end_fill()
            dice.penup()
            dice.goto(295, -30)
            dice.pendown()
            dice.begin_fill()
            dice.circle(width // 15)
            dice.end_fill()
            dice.penup()
            dice.goto(345, 20)
            dice.pendown()
            dice.begin_fill()
            dice.circle(width // 15)
            dice.end_fill()
            dice.penup()
            dice.goto(345, -5)
            dice.pendown()
            dice.begin_fill()
            dice.circle(width // 15)
            dice.end_fill()
            dice.penup()
            dice.goto(345, -30)
            dice.pendown()
            dice.begin_fill()
            dice.circle(width // 15)
            dice.end_fill()
        
            
        DieValue = DieValue + 1

    dice.fillcolor("white")
    dice.penup()
    dice.goto(-120, -150)
    dice.pendown()
    dice.begin_fill()
    for i in range (4):
        dice.forward(width)
        dice.right(90)
    dice.end_fill()
    
    Dice_1 = random.randint(1,6)
    if Dice_1 == 1:
        dice.penup()
        dice.goto(-70, -200)
        dice.fillcolor("Black")
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
    elif Dice_1 == 2:
        dice.penup()
        dice.goto(-95, -225)
        dice.fillcolor("Black")
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
        dice.penup()
        dice.goto(-45, -175)
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
    elif Dice_1 == 3:
        dice.penup()
        dice.goto(-95, -225)
        dice.fillcolor("Black")
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
        dice.penup()
        dice.goto(-70, -200)
        dice.fillcolor("Black")
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
        dice.penup()
        dice.goto(-45, -175)
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
    elif Dice_1 == 4:
        dice.penup()
        dice.goto(-95, -175)
        dice.fillcolor("Black")
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
        dice.penup()
        dice.goto(-95, -225)
        dice.fillcolor("Black")
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
        dice.penup()
        dice.goto(-45, -175)
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
        dice.penup()
        dice.goto(-45, -225)
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
    elif Dice_1 == 5:
        dice.penup()
        dice.goto(-95, -175)
        dice.fillcolor("Black")
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
        dice.penup()
        dice.goto(-95, -225)
        dice.fillcolor("Black")
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
        dice.penup()
        dice.goto(-70, -200)
        dice.fillcolor("Black")
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
        dice.penup()
        dice.goto(-45, -175)
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
        dice.penup()
        dice.goto(-45, -225)
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
    else:
        dice.penup()
        dice.goto(-95, -175)
        dice.fillcolor("Black")
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
        dice.penup()
        dice.goto(-95, -200)
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
        dice.penup()
        dice.goto(-95, -225)
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
        dice.penup()
        dice.goto(-45, -175)
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
        dice.penup()
        dice.goto(-45, -200)
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill
        dice.penup()
        dice.goto(-45, -225)
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
    

    dice.fillcolor("white")
    dice.penup()
    dice.goto(10, -150)
    dice.pendown()
    dice.begin_fill()
    for i in range (4):
        dice.forward(width)
        dice.right(90)
    dice.end_fill()
    
    Dice_2 = random.randint(1,6)
    if Dice_2 == 1:
        dice.penup()
        dice.goto(60, -200)
        dice.fillcolor("Black")
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
    elif Dice_2 == 2:
        dice.penup()
        dice.goto(35, -225)
        dice.fillcolor("Black")
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
        dice.penup()
        dice.goto(85, -175)
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
    elif Dice_2 == 3:
        dice.penup()
        dice.goto(35, -225)
        dice.fillcolor("Black")
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
        dice.penup()
        dice.goto(60, -200)
        dice.fillcolor("Black")
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
        dice.penup()
        dice.goto(85, -175)
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
    elif Dice_2 == 4:
        dice.penup()
        dice.goto(35, -175)
        dice.fillcolor("Black")
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
        dice.penup()
        dice.goto(35, -225)
        dice.fillcolor("Black")
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
        dice.penup()
        dice.goto(85, -175)
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
        dice.penup()
        dice.goto(85, -225)
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
    elif Dice_2 == 5:
        dice.penup()
        dice.goto(35, -175)
        dice.fillcolor("Black")
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
        dice.penup()
        dice.goto(35, -225)
        dice.fillcolor("Black")
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
        dice.penup()
        dice.goto(60, -200)
        dice.fillcolor("Black")
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
        dice.penup()
        dice.goto(85, -175)
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
        dice.penup()
        dice.goto(85, -225)
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
    else:
        dice.penup()
        dice.goto(35, -175)
        dice.fillcolor("Black")
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
        dice.penup()
        dice.goto(35, -200)
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
        dice.penup()
        dice.goto(35, -225)
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
        dice.penup()
        dice.goto(85, -175)
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()
        dice.penup()
        dice.goto(85, -200)
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill
        dice.penup()
        dice.goto(85, -225)
        dice.pendown()
        dice.begin_fill()
        dice.circle(width // 15)
        dice.end_fill()

    dice.penup()
    if Dice_1 + Dice_2 <=7:
        print(format((Dice_1 + Dice_2)/36*100, "2.4f"), "% is the probability of rolling a",Dice_1 + Dice_2)
    else:
        print(format((13-Dice_1-Dice_2)/36*100, "2.4f"),"% is the probability of rolling a",Dice_1 + Dice_2)
                
    

          
if __name__ == "__main__":
    main()
        
